version: "3"
services:
#### postgres ####
  postgres:
    image: postgres:latest
    container_name: postgres1
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1234
    restart: unless-stopped
#### User Management API ####
  usermanagementapi:
    image: user-mngmnt-api:latest
    network_mode: host
    container_name: umapi
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
volumes:
  postgres-data: